#!/bin/bash
pp=$(echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" | sed 's/\r//g')
base=${pp##*/}
name=${base%%.*}

ffmpeg -i "$pp" -vn -acodec libmp3lame -ab 128k -y "${name}.mp3" \
 | zenity --progress --width 600 --title "Converting $base to MP3"
